[[tests]]
name = "first"
input = ["./$project", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
expected = """
 _ | _ | _
---+---+---
 _ | _ | _
---+---+---
 _ | _ | _
O: 0 0
"""
rubric = 10

[[tests]]
name = "offensive1"
input = ["./$project", "O", "_", "O", "X", "_", "X", "_", "_", "_"]
expected = """
 O | _ | O
---+---+---
 X | _ | X
---+---+---
 _ | _ | _
O: 0 1
"""
rubric = 10

[[tests]]
name = "offensive2"
input = ["./$project", "O", "_", "X", "X", "O", "_", "_", "_", "_"]
expected = """
 O | _ | X
---+---+---
 X | O | _
---+---+---
 _ | _ | _
O: 2 2
"""
rubric = 10

[[tests]]
name = "offensive3"
input = ["./$project", "-s", "4", "O", "O", "_", "O", "X", "_", "X", "X", "O", "X", "O", "X",  "O", "X", "O", "X"]
expected = """
 O | O | _ | O
---+---+---+---
 X | _ | X | X
---+---+---+---
 O | X | O | X
---+---+---+---
 O | X | O | X
O: 0 2
"""
rubric = 10

[[tests]]
name = "defensive1"
input = ["./$project", "X", "_", "X", "_", "O", "_", "_", "_", "_"]
expected = """
 X | _ | X
---+---+---
 _ | O | _
---+---+---
 _ | _ | _
O: 0 1
"""
rubric = 10

[[tests]]
name = "defensive2"
input = ["./$project", "X", "_", "O", "_", "X", "_", "_", "_", "_"]
expected = """
 X | _ | O
---+---+---
 _ | X | _
---+---+---
 _ | _ | _
O: 2 2
"""
rubric = 10

[[tests]]
name = "defensive3"
input = ["./$project", "-s", "4", "_", "O", "X", "O", "X", "_", "O", "O", "X", "X", "_", "X", "X", "_", "O", "_"]
expected = """
 _ | O | X | O
---+---+---+---
 X | _ | O | O
---+---+---+---
 X | X | _ | X
---+---+---+---
 X | _ | O | _
O: 0 0
"""
rubric = 10
